config/routes.rb
Rails.application.routes.draw do
  # get 'sections/index'
  # get 'sections/show'
  # get 'sections/new'
  # get 'sections/edit'
  # get 'sections/delete'
  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  
  #auto generated start
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'
  # end
  
  #new added start
  root 'demo#index'
  
  resources :subjects do
    member do
      get :delete
    end
  end
  resources :pages do
    member do
      get :delete
    end
  end
  resources :sections do
    member do
      get :delete
    end
  end

  #end
  
  #  #Simple Route
   get 'demo/index'
   get 'demo/hello'
   get 'demo/hello1'
   get 'demo/youtube'

 
 #Root route
 #root 'demo#index'  #controller#view
 
 
 #Default route
 #get ':controller(/:action(/:id))'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
    #self.table_name = "admin_users" #this way or change file name form User to AdminUser
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
    belongs_to :subject

  scope :visible, lambda {where(:visible => true)}
  scope :invisible, lambda {where(:visible => false)}
  scope :sorted, lambda {order("position ASC")}
  scope :newest_first, lambda {order("created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?","%#{query}%"])}
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :section_edits
  

  scope :visible, lambda {where(:visible => true)}
  scope :invisible, lambda {where(:visible => false)}
  scope :sorted, lambda {order("position ASC")}
  scope :newest_first, lambda {order("created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?","%#{query}%"])}
end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages

    scope :visible, lambda {where(:visible => true)}
    scope :invisible, lambda {where(:visible => false)}
    scope :sorted, lambda {order("position ASC")}
    scope :search, lambda {|query| where(["name LIKE ?","%#{query}%"])}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  def index
    render('index')

  end
  def hello
    @array=[1,2,3,4,5,6,7,8,9]
    render('hello')
  end

  def hello1
  #  redirect_to(:controller => 'demo', :action => 'index')
  redirect_to( :action => 'index')
  end

  def youtube  
      redirect_to('https://youtube.com/', allow_other_host: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'admin'
  def index
    @pages = Page.sorted
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page= Page.new(page_params)
    if @page.save
      flash[:notice] ="Page created successfully......"
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      flash[:notice] ="Page updated successfully......"
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] ="Page '#{@page.name}' delete successfully......"
    redirect_to(pages_path)
  end

  private
  def page_params
    params.required(:page).permit(:subject_id,:name,:position,:visible,:permalink)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  layout false
  def index
    @sections = Section.sorted
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section= Section.new(section_params)
    if @section.save
      flash[:notice] ="Section created successfully......"
      redirect_to(sections_path)
    else
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])

    if @section.update(section_params)
      flash[:notice] = "Section updated successully....."
      redirect_to(section_path(@section))
    else
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end
  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] ="Section '#{@section.name}' delete successfully......"
    redirect_to(sections_path)
  end
  private
  def section_params
    params.required(:section).permit(:page_id,:name,:position,:visible,
    :content_type,:content)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout 'admin'
  def index
    @subjects =Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => 'Default'})
  end

  def create
    @subject= Subject.new(subject_params) # parameters -> (params.required(:subject).permit(:name, :visible))
    if @subject.save
      flash[:notice] = "Subject created successully....."
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end
  
  def update
    @subject = Subject.find(params[:id])

    if @subject.update(subject_params)
      flash[:notice] = "Subject updated successully....."
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end
  
  def delete

    @subject = Subject.find(params[:id])
  end
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}'deleted successully....."
    redirect_to(subjects_path)
  end

  private
  def subject_params
    params.required(:subject).permit(:name,:position,:visible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demo/hello.html.erb
<h1>Hello world form hello file</h1>
<%= 5+5 %> <br />
<% var = "Abinash" %>
<%= "hello #{var}" %>
<% @array.each do |n| %>
<%= n %> <br/>
<% end %>

app/views/demo/index.html.erb
<h1>Hello world 112</h1>
<a href = "/demo/hello">Hello page1</a><br/>
<%= link_to('hello page 2', {:action => 'hello'}) %> <h1>Hello world</h1>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Csgeeks</title>

  </head>

  <body>
    <% if !flash[:notice].blank?%>
    <div class ="notice">
      <%= flash[:notice] %>
    </div>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="Page delete">
  <h1>Delete Subject</h1>
  <%= form_for(@page,:url => page_path(@page),:method => 'delete')do |f| %>
  <p>Are you sure you want to delete this page </p>
  <p class="reference-name"><%= @page.name%></p>


  <div class="form-buttons">
    <%= f.submit("Delete Page")%>
  </div>
  <%end%>
</div>

app/views/pages/edit.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="pages new">
  <h1>Update Page</h1>
  <%= form_for(@page,:url => page_path(@page),:method => 'patch')do |f| %>
  <table summary="Page for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <tr>
        <th>Subject ID</th>
        <td><%= f.text_field(:subject_id)%></td>
      </tr>

      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink)%></td>
      </tr>

      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Update Page")%>
  </div>
  <%end%>
</div>

app/views/pages/index.html.erb
<div class="pages index">
<h1>Pages</h1>
<%= link_to("Add new Page",'pages/new',:class => 'action new')%>
<table class="listing" summary="Page list">
  <tr class="header">
    <th>#</th>
    <th>Subject ID</th>
    <th>Page</th>
    <th>Permalink</th>
    <th>Visible</th>

    <th>Acton</th>
  </tr>
  <% @pages.each do |page|%>
  <tr>
    <td><%= page.position %></td>
    <td><%= page.subject_id %></td>
    <td><%= page.name %></td>
    <td><%= page.permalink %></td>
    <td class="center"><%= page.visible ? 'Yes':'No'%></td>

    <td class = "action">
      <%=link_to("Show",page_path(page),:class=>'acton show')%>
      <%=link_to("Edit",edit_page_path(page),:class=>'acton edit')%>
      <%=link_to("Delete",delete_page_path(page),:class=>'acton delete')%>
    </td>
  </tr>
  <%end%>
</table>





</div>

app/views/pages/new.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="Page new">
  <h1>Create Page</h1>
  <%= form_for(@page,:url => pages_path,:method => 'post')do |f| %>
  <table summary="Page for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Subject ID</th>
      <td><%= f.text_field(:subject_id)%></td>
    </tr>

    <tr>
      <th>Permalink</th>
      <td><%= f.text_field(:permalink)%></td>
    </tr>


    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Create Page")%>
  </div>
  <%end%>
</div>

app/views/pages/show.html.erb
<%= link_to("BACK TO LIST", pages_path, :class => 'back-link')%>
<div class="sujects show">
  <h1>Show Page</h1>
  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <tr>
        <th>Subject ID</th>
        <td><%=  @page.subject_id %></td>
      </tr>

      <tr>
        <th>Permalink</th>
        <td><%=  @page.permalink %></td>
      </tr>

      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>
</div>

app/views/sections/delete.html.erb
<%= link_to("BACK TO LIST", sections_path, :class => 'back-link')%>
<div class="section delete">
  <h1>Delete Section</h1>
  <%= form_for(@section,:url => section_path(@section),:method => 'delete')do |f| %>
  <p>Are you sure you want to delete this section </p>
  <p class="reference-name"><%= @section.name%></p>


  <div class="form-buttons">
    <%= f.submit("Delete Section")%>
  </div>
  <%end%>
</div>

app/views/sections/edit.html.erb
<%= link_to("BACK TO LIST", sections_path, :class => 'back-link')%>
<div class="section new">
  <h1>Update Section</h1>
  <%= form_for(@section ,:url => section_path(@section),:method => 'patch')do |f| %>
  <table summary="Section for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Page ID</th>
      <td><%= f.text_field(:page_id)%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr><tr>
      <th>Content type</th>
      <td><%= f.text_field(:content_type)%></td>
    </tr><tr>
      <th>Content</th>
      <td><%= f.text_field(:content)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Update Section")%>
  </div>
  <%end%>
</div>

app/views/sections/index.html.erb
<div class="sections index">
<h1>Sections</h1>
<%= link_to("Add new Section",'sections/new',:class => 'action new')%>
<table class="listing" summary="Section list">
  <tr class="header">
    <th>#</th>
    <th>Page ID</th>
    <th>Section</th>
    <th>Visible</th>
    <th>Acton</th>
  </tr>
  <% @sections.each do |section|%>
  <tr>
    <td><%= section.position %></td>
    <td><%= section.page_id %></td>
    <td><%= section.name %></td>
    <td class="center"><%= section.visible ? 'Yes':'No'%></td>

    <td class = "action">
      <%=link_to("Show",section_path(section.id),:class=>'acton show')%>
      <%=link_to("Edit",edit_section_path(section.id),:class=>'acton edit')%>
      <%=link_to("Delete",delete_section_path(section.id),:class=>'acton delete')%>
    </td>
  </tr>
  <%end%>
</table>





</div>

app/views/sections/new.html.erb
<%= link_to("BACK TO LIST", sections_path, :class => 'back-link')%>
<div class="section new">
  <h1>Create Section</h1>
  <%= form_for(@section,:url => sections_path,:method => 'post')do |f| %>
  <table summary="Section for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Page ID</th>
      <td><%= f.text_field(:page_id)%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr><tr>
      <th>Content type</th>
      <td><%= f.text_field(:content_type)%></td>
    </tr><tr>
      <th>Content</th>
      <td><%= f.text_field(:content)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Create Section")%>
  </div>
  <%end%>
</div>

app/views/sections/show.html.erb
<%= link_to("BACK TO LIST", sections_path, :class => 'back-link')%>
<div class="sections show">
  <h1>Show Section</h1>
  <table summary="Section detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Page ID</th>
      <td><%= @section.page_id%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr><tr>
      <th>Content type</th>
      <td><%= @section.content_type  %></td>
    </tr><tr>
      <th>Visible</th>
      <td><%= @section.content  %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>
</div>

app/views/subjects/_form.html.erb
<table summary="Subject for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>

app/views/subjects/delete.html.erb
<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="subject delete">
  <h1>Delete Subject</h1>
  <%= form_for(@subject,:url => subject_path(@subject),:method => 'delete')do |f| %>
  <p>Are you sure you want to delete this subject </p>
  <p class="reference-name"><%= @subject.name%></p>


  <div class="form-buttons">
    <%= f.submit("Delete Subject")%>
  </div>
  <%end%>
</div>

app/views/subjects/edit.html.erb
<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="subject new">
  <h1>Update Subject</h1>
  <%= form_for(@subject,:url => subject_path(@subject),:method => 'patch')do |f| %>
  <table summary="Subject for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Update Subject")%>
  </div>
  <%end%>
</div>

app/views/subjects/index.html.erb
<!--<%if !flash[:notice].blank?%>
<div class="notice">
  <%= flash[:notice]%>
</div>
<%end%>
-->
<div class="subjects index">
  <h1>Subjects</h1>
  <%= link_to("Add new Subject", 'subjects/new',:class => 'action new')%>


  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Acton</th>
    </tr>
    <% @subjects.each do |subject|%>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes':'No'%></td>
      <td class="center"><%= subject.pages.size%></td>
      <td class = "action">
        <%=link_to("Show",'subjects/#{subject.id}',:class=>'acton show')%>
       <!-- <%=link_to("Show",{:controller => 'subjects', :action => 'show', :id => subject.id},:class=>'acton show')%> -->
       <!-- <%=link_to("Show",subject_path(subject.id),:class=>'acton show')%>  -->
        <%=link_to("Edit",edit_subject_path(subject.id),:class=>'acton edit')%>
        
        <%=link_to("Delete",delete_subject_path(subject.id),:class=>'acton delete')%>
      </td>
    </tr>
    <%end%>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="subject new">
  <h1>Create Subject</h1>
  <%= form_for(@subject,:url => subjects_path,:method => 'post')do |f| %>
  <table summary="Subject for fields">
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:name)%></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= f.text_field(:position)%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= f.text_field(:visible)%></td>
    </tr>
  </table>
  <div class="form-buttons">
    <%= f.submit("Create Subject")%>
  </div>
  <%end%>
</div>

app/views/subjects/show.html.erb
<!--
<%if !flash[:notice].blank?%>
<div class="notice">
  <%= flash[:notice]%>
</div>
<%end%> -->

<%= link_to("BACK TO LIST", subjects_path, :class => 'back-link')%>
<div class="sujects show">
  <h1>Show Subject</h1>
  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>
</div>